-- ====================================================================
-- 🛡️ GuardianAI Supabase Database Schema & Realtime Setup
-- ====================================================================
-- Run this script inside your Supabase Project -> SQL Editor -> Run

-- 1. Create table: guardian_users
CREATE TABLE IF NOT EXISTS public.guardian_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    role VARCHAR(20) DEFAULT 'user',
    is_verified BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    last_latitude DOUBLE PRECISION DEFAULT 17.3850,
    last_longitude DOUBLE PRECISION DEFAULT 78.4867,
    last_address VARCHAR(255) DEFAULT 'Hyderabad, Telangana',
    battery_level INTEGER DEFAULT 85,
    fcm_token TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create table: emergency_alerts (SOS Telemetry & Dispatch)
CREATE TABLE IF NOT EXISTS public.emergency_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(150) NOT NULL,
    user_phone VARCHAR(20) NOT NULL,
    user_role VARCHAR(20) DEFAULT 'user',
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    address VARCHAR(255) DEFAULT 'Live Location',
    trigger_source VARCHAR(30) DEFAULT 'button',
    status VARCHAR(20) DEFAULT 'active',
    siren_active BOOLEAN DEFAULT TRUE,
    battery_level INTEGER DEFAULT 100,
    responder_name VARCHAR(150) DEFAULT NULL,
    notes TEXT DEFAULT '',
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ DEFAULT NULL
);

-- 3. Create table: otp_records
CREATE TABLE IF NOT EXISTS public.otp_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target VARCHAR(100) NOT NULL,
    otp_code VARCHAR(6) NOT NULL,
    purpose VARCHAR(50) DEFAULT 'registration',
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

-- 4. Create table: emergency_contacts
CREATE TABLE IF NOT EXISTS public.emergency_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_phone VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    relationship VARCHAR(50) DEFAULT 'Family',
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- ⚡ Enable Supabase Realtime (Live Emergency Radar)
-- ====================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.emergency_alerts;
ALTER PUBLICATION supabase_realtime ADD TABLE public.guardian_users;

-- ====================================================================
-- 🔒 Enable Row Level Security (RLS)
-- ====================================================================
ALTER TABLE public.guardian_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otp_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_contacts ENABLE ROW LEVEL SECURITY;

-- Allow public / backend read & write policies
CREATE POLICY "Allow anonymous read alerts" ON public.emergency_alerts FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert alerts" ON public.emergency_alerts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update alerts" ON public.emergency_alerts FOR UPDATE USING (true);

CREATE POLICY "Allow anonymous read users" ON public.guardian_users FOR SELECT USING (true);
CREATE POLICY "Allow anonymous upsert users" ON public.guardian_users FOR ALL USING (true);

CREATE POLICY "Allow anonymous otp insert" ON public.otp_records FOR ALL USING (true);
CREATE POLICY "Allow anonymous contacts insert" ON public.emergency_contacts FOR ALL USING (true);
